baseURL = 'https://binhphan421.github.io/blog/'
languageCode = 'en-us'
title = 'Binh'
theme = 'stack'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"

[params]
  mainSections = ["posts"]
  featuredImageField = "image"
  rssFullContent = true

  [params.favicon]

  [params.footer]
    since = ""
    customText = ""

  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
    compact = false
    emoji = ""
    subtitle = "Since I cannot speak, I write."

    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "pepper.jpg"

  [params.article]
    headingAnchor = false
    math = false
    toc = true
    readingTime = false

    [params.article.license]
      enabled = false
      default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
    enabled = false

  [params.widgets]
    page = []

  [[params.widgets.homepage]]
    type = "categories"
    [params.widgets.homepage.params]
      limit = 10

  [params.opengraph]
    [params.opengraph.twitter]
      site = ""
      card = "summary_large_image"

  [params.defaultImage]
    [params.defaultImage.opengraph]
      enabled = false
      local = false
      src = ""

  [params.colorScheme]
    toggle = false
    default = "dark"

  [params.imageProcessing]
    [params.imageProcessing.cover]
      enabled = true

    [params.imageProcessing.content]
      enabled = true

[[menu.social]]
  identifier = "instagram"
  name = "Instagram"
  url = "https://www.instagram.com/binhphan421/"
  [menu.social.params]
      icon = "brand-instagram"