baseURL = 'https://binhphan421.github.io/blog/'
languageCode = 'en-us'
title = 'Binh'
theme = 'stack'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"

[params]
  mainSections = ["posts"]
  featuredImageField = "image"
  rssFullContent = true

  [params.favicon]

  [params.footer]
    since = ""
    customText = ""

  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
    compact = false
    emoji = ""
    subtitle = "Since I cannot speak, I write."

    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "pepper.jpg"

  [params.article]
    headingAnchor = false
    math = false
    toc = true
    readingTime = false

    [params.article.license]
      enabled = false
      default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
    enabled = false
    provider = "disqus"

    [params.comments.disqusjs]
      shortname = ""
      apiUrl = ""
      apiKey = ""
      admin = ""
      adminLabel = ""

    [params.comments.utterances]
      repo = ""
      issueTerm = "pathname"
      label = ""

    [params.comments.beaudar]
      repo = ""
      issueTerm = "pathname"
      label = ""
      theme = ""

    [params.comments.remark42]
      host = ""
      site = ""
      locale = ""

    [params.comments.vssue]
      platform = ""
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
      autoCreateIssue = false

    [params.comments.waline]
      serverURL = ""
      lang = ""
      visitor = ""
      avatar = ""
      emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
      requiredMeta = ["nick", "mail"]

      [params.comments.waline.locale]
        admin = "Admin"
        placeholder = ""

    [params.comments.twikoo]
      envId = ""
      region = ""
      path = ""
      lang = ""

    [params.comments.giscus]
      repo = ""
      repoID = ""
      category = ""
      categoryID = ""
      mapping = ""
      strict = ""
      lightTheme = ""
      darkTheme = ""
      reactionsEnabled = 1
      emitMetadata = 0
      inputPosition = ""
      lang = ""

    [params.comments.gitalk]
      owner = ""
      admin = ""
      repo = ""
      clientID = ""
      clientSecret = ""

    [params.comments.cusdis]
      host = ""
      id = ""

  [params.widgets]
    homepage = []
    page = []

  [params.opengraph]
    [params.opengraph.twitter]
      site = ""
      card = "summary_large_image"

  [params.defaultImage]
    [params.defaultImage.opengraph]
      enabled = false
      local = false
      src = ""

  [params.colorScheme]
    toggle = false
    default = "dark"

  [params.imageProcessing]
    [params.imageProcessing.cover]
      enabled = true

    [params.imageProcessing.content]
      enabled = true
