baseURL = 'https://binhphan421.github.io/blog/'
languageCode = 'en-us'
title = 'Binh'
theme = 'bilberry'

[module]
  [[module.imports]]
    path = "bilberry/v4"

[params]
  permanentTopNav = true
  customImage = "site/pepper.jpg"
  subtitle = "Since I cannot speak, I write."
  baseColor = "#F05941" 
  specialColor = "#BE3144"
  highlightColor = "#872341"
  pageBackgroundColor = "#191919"
  headerTextColor = "#f1f1f1"
  textColor = "#f1f1f1"
  connectionLineColor = "#444"
  connectionDotColor = "#444"
  bubbleBackgroundColor = "#373737"
  articleBackgroundColor = "#222"
  metaTextcolor = "darken(#f1f1f1,40)"
  footerBorderColor = "#F05941"
  footerBackgroundColor = "#191919"
  footerHeadlineColor = "#BE3144"
  css_modules = [ "css/custom.css" ]
  paginate = 10

  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.article]
    headingAnchor = false
    math = false
    toc = true
    readingTime = false

  [params.comments]
    enabled = false

[[menu.social]]
  identifier = "instagram"
  name = "Instagram"
  url = "https://www.instagram.com/binhphan421/"
  [menu.social.params]
      icon = "brand-instagram"