baseURL = 'https://binhphan421.github.io/blog/'
languageCode = 'en-us'
title = 'Binh'
theme = 'bilberry'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"

[params]
  mainSections = ["posts"]
  featuredImageField = "image"
  rssFullContent = true
  enableLightDarkTheme = true
  permanentTopNav = true
  customImage = "site/pepper.jpg"
  subtitle = "Since I cannot speak, I write."

  [params.favicon]

  [params.footer]
    since = ""
    customText = ""

  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.article]
    headingAnchor = false
    math = false
    toc = true
    readingTime = false

  [params.comments]
    enabled = false

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = -100
  [menu.main.params]
    icon = "home"

[[menu.social]]
  identifier = "instagram"
  name = "Instagram"
  url = "https://www.instagram.com/binhphan421/"
  [menu.social.params]
      icon = "brand-instagram"